# Commands that will be executed when level is up
# - structure: "%level%, %console/player%:%command%"
# - 'console:cmd' - run command by console
# - 'player:cmd' - run command by player
up-level-commands:
  - "5, console:give %player% minecraft:diamond_pickaxe"
  - "10, console:say %player% has %level% level"
  - "10, console:say %player% has %level% level!!!"
  - "12, console:money add %player% 1000"
  - "14, player:tell console I'm the best"

# Levels settings
levels:
  1: 300
  2: 400
  3: 500
  4: 350

# What percent of xp player (on his current level) will lose on die by another player
pvp-xp-loose: 100.0

# What percent of xp player (on his current level) will lose on another die reasons
pve-xp-loose: 0.0